# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 17:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=140)),
                ('virtual', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('caducidad', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(max_length=120)),
                ('calle', models.CharField(max_length=120)),
                ('numero', models.CharField(max_length=8)),
                ('lado', models.CharField(max_length=80)),
                ('frentre', models.CharField(max_length=80)),
                ('casa', models.CharField(choices=[(b'1 piso', b'1 piso'), (b'2 pisos', b'2 pisos')], max_length=8)),
                ('fachada', models.CharField(max_length=80)),
                ('entre', models.CharField(max_length=120)),
                ('municipio', models.CharField(max_length=120)),
                ('lon', models.FloatField(blank=True, default=1.63789, null=True)),
                ('lat', models.FloatField(blank=True, default=-77.7452081, null=True)),
                ('estado', models.CharField(blank=True, choices=[(b'Vigente', b'Vigente'), (b'Cancelado', b'cancelado'), (b'incobrabrle', b'incobrabrle')], default=b'Vigente', max_length=25, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('existencia', models.IntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Almacen')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Articulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=180)),
                ('colonia', models.CharField(max_length=150)),
                ('celular', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=80)),
                ('municipio', models.CharField(max_length=80)),
                ('estatus', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
