# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 17:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cxc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tipo', models.IntegerField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('abono', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('proxcobro', models.DateField(blank=True, null=True)),
                ('fechaabono', models.DateField(blank=True, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('enganche', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fechaventa', models.DateField(blank=True, null=True)),
                ('apartir', models.DateField()),
                ('abono', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observacion', models.TextField()),
                ('tipocobro', models.CharField(choices=[(b'Semana', b'Semana'), (b'Quincena', b'Quincena'), (b'Mes', b'Mes')], default=b'Semana', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cliente')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Inventario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Vendedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cxc',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Venta'),
        ),
    ]
